// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // Generated by `make typegen` (wrangler types): runtime + binding typings per worker
    ignores: ['**/worker-configuration.d.ts']
  },
  {
    rules: {
      // Factory pattern is acceptable for test data factories (ADR-003)
      '@typescript-eslint/no-extraneous-class': 'off'
    }
  }
)
