import {describe, it, expect} from 'vitest'
import {existsSync} from 'node:fs'
import {
    CHANNELS, LEAVES, MODES, NO_OVERRIDE, buildPairs, createResolver, meetsThreshold, referencesFor,
    repoFile, repoPath, round, type Mode, type Pair
} from './designSystemPairs'
import {contrastRatio, composite, hexToRgb, oklchToHex, parsePaletteOverrides, rgbToOklch, withLightness} from './contrast'
import {PALETTES_UNDER_TEST} from './palettes'
import {BASE_PALETTE, PRESETS} from '../../../scripts/palettes/presets'
import {renderPreset} from '../../../scripts/palettes/render'

/**
 * Architecture test - EN 301 549 / WCAG 2.1 contrast across the design-system tokens.
 *
 * This asserts a *property* of the palette, never a token value (docs/testing.md forbids
 * `expect(token).toContain('text-lg')`): it resolves every colour the design system names
 * through the same stylesheets the browser reads, composites the alpha surfaces, and
 * measures the contrast ratio WCAG 2.1 defines. The pairs are derived by walking the design
 * system, so a token added tomorrow is measured tomorrow - nothing is typed out twice.
 *
 * The inventory, the resolution order and the scoping rules live in `designSystemPairs.ts`,
 * because `scripts/palettes/render.ts` solves the same pairs it is measured by. Which palettes are
 * measured, and at which level, comes from the registry the appearance card badges (`palettes.ts`),
 * so the promise a member reads and the assertion here are one value.
 *
 * Levels (WCAG 2.1, adopted by EN 301 549 clause 9.1.4):
 *   1.4.3  Contrast (Minimum), AA   - 4.5:1 body text, 3:1 large-scale text   → every palette today
 *   1.4.6  Contrast (Enhanced), AAA - 7:1 body text, 4.5:1 large-scale text   → a preset the registry badges AAA
 *   1.4.11 Non-text Contrast, AA    - 3:1 borders, rings, UI boundaries (no AAA level exists)
 *
 * When a case fails, fix the token - never the threshold. A pair a palette cannot meet is listed in
 * PRESET_FINDINGS with the ratio it reaches and runs as `it.fails`, so both a regression in a green
 * pair and a fix of a listed one break the build. Every palette meets its level today.
 */

// ---------------------------------------------------------------------------
// The palettes: the base every visitor sees plus the presets the appearance preference offers
// ---------------------------------------------------------------------------

/**
 * The palettes and their levels come from `PALETTES_UNDER_TEST`, which derives them from the
 * registry the appearance card badges - so the level a member is promised is the level asserted
 * here, and flipping the registry moves the assertion with it. Each stylesheet is generated by
 * `scripts/palettes/generate.ts` and measured on its own, because it applies on its own: the base
 * (`default.css`, Glade farver) wherever no `data-palette` is set, a preset under its own. A registry
 * entry with no file is a badge nobody measured, so its case fails rather than skips.
 */
const PALETTES = PALETTES_UNDER_TEST

/**
 * The regeneration case runs a full solve, a few seconds for an AAA preset and several times that
 * beside the full suite
 */
const RENDER_TIMEOUT_MS = 30_000

/**
 * Pairs a palette cannot answer, keyed `<palette>|<pair>`, with the ratio it reaches. They run as
 * `it.fails`, so a regeneration that fixes one breaks the build and asks for the entry to go.
 *
 * Glade farver and Til farveblinde meet AA on every pair, in light and dark. The nine tokens that used to
 * hold them back drew one rung as a fill and as ink at once; each now carries its own `dark:` face
 * (`*_CALENDAR.day.next`, `PLANNING_CALENDAR.day.potential`, `BORDER.amber[500]`, `RING.amber[500]`,
 * `BORDER.gray[800]`, `TEXT.dimmed`, `COMPONENTS.powerMode.iconClass`), and the two countdown
 * accents moved to the 200 rung, which only they draw.
 *
 * Høj kontrast meets AAA on every pair since 2026-09-18, through two changes: the generator gives
 * up chroma where sRGB cannot show a rung at its new lightness (a clipped channel costs the
 * luminance the lift was for), and `BORDER.orange[500]` draws the 600 rung in light mode, so the
 * border no longer shares its rung with the orange band fill.
 */
const PRESET_FINDINGS = new Map<string, number>([])

/** The selectors a stylesheet opens its blocks with, its comments left out */
const blockSelectors = (css: string) =>
    [...css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/([^{}]+)\{/g)].map(([, selector]) => selector!.trim())

/**
 * CSS specificity (ids, classes, types) of a compound selector of the shapes a palette block uses:
 * `html`, `.dark`, `[data-palette="…"]`, and `:not(…)`, which counts as its argument
 */
const specificity = (selector: string): [number, number, number] => {
    const bare = selector.replace(/:not\(([^)]*)\)/g, ' $1')
    return [
        (bare.match(/#[\w-]+/g) ?? []).length,
        (bare.match(/\.[\w-]+|\[[^\]]+\]|:[\w-]+/g) ?? []).length,
        (bare.match(/(^|[\s>+~])[a-z]+/g) ?? []).length
    ]
}

/** What Nuxt UI's colours plugin writes its variables under at runtime: `:root` and `.dark` */
const NUXT_UI_RUNTIME: [number, number, number] = [0, 1, 0]

const outranks = (a: [number, number, number], b: [number, number, number]) =>
    a[0] !== b[0] ? a[0] > b[0] : a[1] !== b[1] ? a[1] > b[1] : a[2] > b[2]

describe('EN 301 549 / WCAG 2.1: the design system meets its contrast level', () => {
    it('the OKLCH conversion agrees with the sRGB hex Tailwind 4 publishes', () => {
        // Tailwind ships its default palette in oklch(); these are its documented hex values,
        // so a drift in the OKLab matrix or the gamma curve shows up here before anywhere else
        expect({
            green500: oklchToHex('oklch(72.3% 0.219 149.579)'),
            gray500: oklchToHex('oklch(55.1% 0.027 264.364)'),
            red500: oklchToHex('oklch(63.7% 0.237 25.331)'),
            gray50: oklchToHex('oklch(98.5% 0.002 247.839)')
        }).toEqual({green500: '#00c950', gray500: '#6a7282', red500: '#fb2c36', gray50: '#f9fafb'})
    })

    it('the OKLCH inverse returns the lightness, chroma and hue the forward conversion took', () => {
        // The generator moves a published hex along L with its hue and chroma held, so the
        // round trip is the guarantee that "darker Mocha Mousse" is still Mocha Mousse
        const mocha = rgbToOklch(hexToRgb('#a47864'))
        expect({
            lightness: Math.round(mocha.lightness * 1000) / 1000,
            chroma: Math.round(mocha.chroma * 1000) / 1000,
            hue: Math.round(mocha.hue * 10) / 10
        }).toEqual({lightness: 0.611, chroma: 0.063, hue: 45.5})
        // The generator reads a hex, moves L and writes a hex, so the round trip has to land
        // on the byte it started from for every family the palette publishes
        expect(['#a47864', '#fa7b95', '#3c8c9e', '#6a7282'].map(hex => withLightness(hex, rgbToOklch(hexToRgb(hex)).lightness)))
            .toEqual(['#a47864', '#fa7b95', '#3c8c9e', '#6a7282'])
    })

    it('the contrast ratio matches the WCAG 2.1 reference values', () => {
        const white = hexToRgb('#ffffff')
        expect(round(contrastRatio(hexToRgb('#000000'), white))).toBe(21)
        expect(round(contrastRatio(white, white))).toBe(1)
        // #767676 on white is the canonical "just passes AA" grey of the WCAG techniques
        expect(round(contrastRatio(hexToRgb('#767676'), white))).toBe(4.54)
        // 50% black over white composites to the mid grey, and measures as that grey
        expect(contrastRatio(composite({...hexToRgb('#000000'), alpha: 0.5}, white), white))
            .toBeCloseTo(contrastRatio(hexToRgb('#808080'), white), 1)
    })

    it('every palette shade the design system names resolves to a value', () => {
        const resolve = createResolver(NO_OVERRIDE.light)
        // `bg-<family>-<shade>` is the shape that can name a family no stylesheet declares -
        // `bg-mocha-500` would paint nothing, because `--color-mocha-500` is never emitted
        const isShade = (reference: string) => /^[a-z]+-\d{2,3}(\/\d+)?$/.test(reference)
        const unresolved = LEAVES.flatMap(leaf =>
            MODES.flatMap((mode: Mode) => {
                const references = referencesFor(leaf.classes, mode)
                return CHANNELS.flatMap(channel => (references[channel] ?? [])
                    .filter(reference => isShade(reference) && !resolve(reference, channel, mode))
                    .map(reference => `${leaf.path} (${mode}) - ${channel}-${reference}`))
            })
        )
        expect([...new Set(unresolved)].join('\n')).toBe('')
    })

    it('every listed finding still names a pair of the default inventory', () => {
        // A finding whose pair left the inventory - a token renamed, a scoping rule that put it
        // outside 1.4.3 or 1.4.11 - is a line nothing measures any more, and it goes
        const measured = new Set(buildPairs(NO_OVERRIDE, 'AA').map(pair => pair.key))
        const stale = [...PRESET_FINDINGS.keys()].map(key => key.split('|').slice(1).join('|'))
        expect(stale.filter(key => !measured.has(key)).join('\n')).toBe('')
    })

    it('the generator solves the presets the registry badges, at the level and the colour safety it badges them', () => {
        // Three copies of a level would let the badge promise AAA while the spec measures AA, and a
        // registry that claims colour safety for a preset the generator does not separate would
        // badge a promise nobody solved for. The registry is the source; this keeps the producer on it
        const solved = PRESETS.map(({name, level, colourSafe}) => `${name} ${level}${colourSafe ? ' colour-safe' : ''}`).sort()
        const badged = PALETTES.filter(palette => palette.promised)
            .map(palette => `${palette.id} ${palette.promised}${palette.colourSafe ? ' colour-safe' : ''}`).sort()
        expect(solved).toEqual(badged)
    })

    describe.each(PALETTES)('$label', palette => {
        const {id, file, level} = palette
        const published = file !== null && existsSync(repoPath(file))
        const override = published ? parsePaletteOverrides(repoFile(file!)) : null

        if (file !== null) {
            it('publishes the stylesheet its badge claims', () => {
                // A registry entry with no generated file badges a level nobody measured
                expect(published, `${file} is missing - run npx jiti scripts/palettes/generate.ts`).toBe(true)
            })

            it('is generated from the preset the generator holds today', () => {
                const preset = PRESETS.find(candidate => candidate.name === id)
                expect(preset, `no preset named ${id} in scripts/palettes/presets.ts`).toBeDefined()
                expect(published ? repoFile(file) : '',
                    `${file} is stale - run make palettes (npx jiti scripts/palettes/generate.ts) and commit the result`)
                    .toBe(renderPreset(preset!))
            }, RENDER_TIMEOUT_MS)

            it('applies on its own, above the variables Nuxt UI writes at runtime', () => {
                // Each stylesheet is measured alone, which is what the browser paints only when two
                // palettes never apply together: the base steps aside wherever a preset is chosen,
                // and a preset applies under its own data-palette only
                const scope = id === BASE_PALETTE ? ':not([data-palette])' : `[data-palette="${id}"]`
                const selectors = published ? blockSelectors(repoFile(file)) : []
                expect(selectors.filter(selector => !selector.includes(scope) || !outranks(specificity(selector), NUXT_UI_RUNTIME)))
                    .toEqual([])
                expect(selectors).toHaveLength(2)
            })
        }

        // A preset with no stylesheet has already failed above; its pairs would measure the
        // published palette and say nothing about the preset, so they do not run
        const pairs = file !== null && !published ? [] : buildPairs(override ?? NO_OVERRIDE, level)
        const groups = [...new Set(pairs.map(pair => pair.group))]

        describe.each(groups)('%s', group => {
            const cases = pairs.filter(pair => pair.group === group)
            const finding = (pair: Pair) => PRESET_FINDINGS.get(`${id}|${pair.key}`)

            const green = cases.filter(pair => finding(pair) === undefined)
                .map(pair => ({pair, name: `${pair.mode}: ${pair.name} ≥ ${pair.threshold} (${level})`}))


            const findings = cases.filter(pair => finding(pair) !== undefined)
                .map(pair => ({
                    pair,
                    name: `${pair.mode}: ${pair.name} — ${finding(pair)} (finding 2026-09-18, awaiting the user's decision)`
                }))

            it.each(green)('$name', ({pair}) => {
                expect(meetsThreshold(pair), `${pair.name} measures ${round(pair.ratio)}:1`).toBe(true)
            })

            it.fails.each(findings)('$name', ({pair}) => {
                expect(meetsThreshold(pair), `${pair.name} measures ${round(pair.ratio)}:1`).toBe(true)
            })
        })
    })
})
