/**
 * The palette presets `scripts/palettes/generate.ts` emits - the data, with no side effects, so a
 * spec can read what the generator solves without running it.
 *
 * The level a preset is generated against is the level `PALETTES` in
 * `app/composables/useUserPreferenceValidation.ts` badges it with and
 * `tests/component/architecture/designSystemContrast.unit.spec.ts` asserts it at;
 * that spec fails when the two lists disagree.
 */

import type {Level} from '../../tests/component/architecture/designSystemPairs'
import {CUD_ANCHORS} from '../../tests/component/architecture/colourVision'

/** Where a preset publishes its blocks, relative to the repository root */
export const paletteFile = (name: string) => `app/assets/css/palettes/${name}.css`

/** The registry key of the palette a member gets without choosing: the base every visitor sees */
export const BASE_PALETTE = 'default'

/**
 * The selector a preset's blocks render under. The base applies wherever no `data-palette` is set,
 * so it never sits beneath a chosen preset; a preset applies under its own `data-palette`. Every
 * selector outranks the `:root` and `.dark` variables Nuxt UI's colours plugin writes at runtime.
 */
export const paletteSelector = (name: string, mode: 'light' | 'dark') => {
    const root = mode === 'dark' ? 'html.dark' : 'html'
    return name === BASE_PALETTE ? `${root}:not([data-palette])` : `${root}[data-palette="${name}"]`
}

/**
 * One family of a hue map: the anchor it takes, what the anchor means in the app, and how the
 * preset publishes it. `scale` redeclares `--color-<family>-<step>`; `slot` redeclares
 * `--ui-color-<slot>-<step>`, which paints `text-<slot>-600` and `bg-<slot>` while the brand
 * family the slot aliases keeps its published value.
 *
 * Every rung takes the anchor's hue. It takes the anchor's chroma too, clamped to the sRGB gamut,
 * unless `chroma` is `ladder`: a family that also paints the app's greys keeps the tint strength of
 * the ladder it walks, so its text and surfaces stay greys in the anchor's hue.
 */
export type Anchor = {hex: string, meaning: string, as: 'scale' | 'slot', ladder: string, chroma?: 'anchor' | 'ladder'}

/** family or Nuxt UI slot → the anchor it takes */
export type HueMap = Record<string, Anchor>

/**
 * A colour-safe preset keeps its meanings apart under protanopia, deuteranopia and tritanopia:
 * `scripts/palettes/render.ts` spreads its meaning faces against the meaning inventory, and
 * `stops` are the colours `RAINBOW` publishes, one per stop in stop order.
 */
export type ColourSafety = {stops: readonly string[]}

export type Preset = {
    name: string
    level: Level
    /** Bumped when the preset is regenerated, so a rerun that changes nothing changes no byte */
    generatedOn: string
    hues: HueMap
    /** Set when the registry badges the preset colour-safe (`PALETTES` in useUserPreferenceValidation.ts) */
    colourSafe?: ColourSafety
    /** The lines of the file's opening comment, between `/*` and the closing marker */
    header: (output: string, generatedOn: string) => string[]
}

const baseHeader = (output: string, generatedOn: string) => [
    ' * Glade farver - the AA base palette every visitor sees. GENERATED by scripts/palettes/generate.ts;',
    ' * edits are overwritten.',
    ' *',
    ' * It applies wherever no `data-palette` is set, under selectors that outrank the `:root` and `.dark`',
    ' * variables Nuxt UI writes at runtime; a chosen preset replaces it rather than layering on it.',
    ' *',
    ` * Generated ${generatedOn} against EN 301 549 → WCAG 2.1: 4.5:1 body text and 3:1 large-scale`,
    ' * text (1.4.3 AA), 3:1 borders, rings and UI boundaries (1.4.11 AA). The hues and the chroma are',
    ' * TheSlope\'s published palette; only OKLCH lightness moves, and the neutral surfaces stay put.',
    ' *',
    ' * A `--ui-<slot>` line re-points a Nuxt UI semantic slot at another rung of its own family,',
    ' * so a white button label is answered by the slot rather than by the rung the brand paints with.',
    ' *',
    ` * Run: npx jiti scripts/palettes/generate.ts     # rewrites ${output}`
]

const highContrastHeader = (output: string, generatedOn: string) => [
    ' * Høj kontrast - the AAA palette preset. GENERATED by scripts/palettes/generate.ts; edits are',
    ' * overwritten.',
    ' *',
    ` * Generated ${generatedOn} against EN 301 549 → WCAG 2.1: 7:1 body text and 4.5:1 large-scale`,
    ' * text (1.4.6 AAA), 3:1 borders, rings and UI boundaries (1.4.11 AA). The base\'s procedure one',
    ' * level up: the hues and the chroma are TheSlope\'s published palette; only OKLCH lightness',
    ' * moves, and the neutral surfaces stay put.',
    ' *',
    ' * A `--ui-<slot>` line re-points a Nuxt UI semantic slot at another rung of its own family,',
    ' * so a white button label is answered by the slot rather than by the rung the brand paints with.',
    ' *',
    ` * Run: npx jiti scripts/palettes/generate.ts     # rewrites ${output}`
]

const colorblindHeader = (output: string, generatedOn: string) => [
    ' * Til farveblinde - the colour-safe AA palette preset. GENERATED by scripts/palettes/generate.ts;',
    ' * edits are overwritten.',
    ' *',
    ` * Generated ${generatedOn}. Every meaning takes a Color Universal Design (Okabe & Ito) colour,`,
    ' * and the set stays apart under protanopia, deuteranopia and tritanopia: success bluish green',
    ' * #009E73, error vermillion #D55E00, warning orange #E69F00, deadline chips yellow #F0E442, info',
    ' * blue #0072B2, secondary and the cooking day reddish purple #CC79A7, neutral sky blue #56B4E9,',
    ' * primary black #000000. A family takes its anchor\'s hue and chroma on the published family\'s',
    ' * lightness ladder, chroma clamped to the sRGB gamut per rung; neutral keeps the ladder\'s chroma,',
    ' * so the greys it paints stay greys.',
    ' *',
    ' * The info, primary and neutral slots are published as `--ui-color-<slot>-<step>`, so the slot',
    ' * takes its colour while the brand family behind it - violet, amber, sky - keeps painting the',
    ' * bands, the frame and the chips.',
    ' *',
    ' * A meaning face - the fill a solid badge and a button show - takes its anchor\'s hue and at least',
    ' * half its chroma, at the anchor\'s own lightness where AA allows. Where AA does not, the faces take',
    ' * the arrangement nearest their anchors\' lightness that keeps every two meanings shown together',
    ' * apart for a dichromat. Black aims for the ink end: black on a light page, white on a dark one.',
    ' *',
    ' * The eight team stops are the eight colours of the set, team 9 repeating team 1.',
    ' *',
    ' * On top of the hue map the preset meets EN 301 549 → WCAG 2.1: 4.5:1 body text and 3:1',
    ' * large-scale text (1.4.3 AA), 3:1 borders, rings and UI boundaries (1.4.11 AA), in both modes.',
    ' * A `--ui-<slot>` line re-points a Nuxt UI semantic slot at another rung of its own family,',
    ' * so a white button label is answered by the slot rather than by the rung the brand paints with.',
    ' *',
    ` * Run: npx jiti scripts/palettes/generate.ts     # rewrites ${output}`
]

/**
 * Til farveblinde's hue map. The frame families stay put - amber (the Mocha frame) and blue (the header)
 * - and so do ocean, party, peach, caramel, winery, sky and the Bonbon violet. Orange is both band 1
 * and the warning slot, and the anchor sits 36° from Mandarin Orange, so the scale moves and the band
 * moves with it. Info, primary and neutral are slots over violet, amber and sky, so the slot moves
 * alone.
 */
const COLORBLIND_HUES: HueMap = {
    green: {hex: CUD_ANCHORS.bluishGreen, meaning: 'success, active season, CHILD ticket, holiday ring', as: 'scale', ladder: 'green'},
    red: {hex: CUD_ANCHORS.vermillion, meaning: 'error, released orders, cancellations, delete confirm', as: 'scale', ladder: 'red'},
    orange: {hex: CUD_ANCHORS.orange, meaning: 'warning, power mode, deadline ring, CTAs', as: 'scale', ladder: 'orange'},
    yellow: {hex: CUD_ANCHORS.yellow, meaning: 'deadline chips', as: 'scale', ladder: 'yellow'},
    pink: {hex: CUD_ANCHORS.reddishPurple, meaning: 'secondary, generated cooking days, picker selection', as: 'scale', ladder: 'pink'},
    info: {hex: CUD_ANCHORS.blue, meaning: 'info alerts, guest rows, claimed orders', as: 'slot', ladder: 'violet'},
    primary: {hex: CUD_ANCHORS.black, meaning: 'primary buttons and links, normal orders, ADULT ticket', as: 'slot', ladder: 'amber'},
    neutral: {hex: CUD_ANCHORS.skyBlue, meaning: 'neutral, BABY ticket, and the greys the slot paints', as: 'slot', ladder: 'sky', chroma: 'ladder'}
}

/**
 * Til farveblinde's team stops, in `RAINBOW` order: all eight colours of the set. A stop takes a colour
 * its ink can carry at the colour's own lightness - Bonbon, Sky and Mocha carry white ink, and of the
 * set only black and blue carry white, so vermillion takes the third white stop and darkens as far
 * as AA asks. Peach's stop rung, `peach-300`, is also the peach slot's face on a dark page, which
 * lifts it; sky blue lifts away from every other stop, bluish green would lift into sky blue.
 */
const COLORBLIND_STOPS = [
    CUD_ANCHORS.reddishPurple,  // pink
    CUD_ANCHORS.orange,         // orange
    CUD_ANCHORS.bluishGreen,    // ocean
    CUD_ANCHORS.vermillion,     // bonbon, white ink
    CUD_ANCHORS.skyBlue,        // peach
    CUD_ANCHORS.yellow,         // yellow
    CUD_ANCHORS.blue,           // sky, white ink
    CUD_ANCHORS.black           // mocha, white ink
] as const

export const PRESETS: Preset[] = [
    {name: BASE_PALETTE, level: 'AA', generatedOn: '2026-09-18', hues: {}, header: baseHeader},
    {name: 'high-contrast', level: 'AAA', generatedOn: '2026-09-18', hues: {}, header: highContrastHeader},
    {name: 'colorblind', level: 'AA', generatedOn: '2026-09-18', hues: COLORBLIND_HUES, colourSafe: {stops: COLORBLIND_STOPS}, header: colorblindHeader}
]
