/**
 * The palette presets `scripts/palettes/generate.ts` emits - the data, with no side effects, so a
 * spec can read what the generator solves without running it.
 *
 * The level a preset is generated against is the level `PALETTES` in
 * `app/composables/useUserPreferenceValidation.ts` badges it with and
 * `tests/component/architecture/designSystemContrast.unit.spec.ts` asserts it at;
 * that spec fails when the two lists disagree.
 */

import type {Level} from '../../tests/component/architecture/designSystemPairs'

/** Where a preset publishes its `html[data-palette]` block, relative to the repository root */
export const paletteFile = (name: string) => `app/assets/css/palettes/${name}.css`

/**
 * One family of a hue map: the anchor it takes, what the anchor means in the app, and how the
 * preset publishes it. `scale` redeclares `--color-<family>-<step>`; `slot` redeclares
 * `--ui-color-<slot>-<step>`, which paints `text-<slot>-600` and `bg-<slot>` while the brand
 * family the slot aliases keeps its published value.
 */
export type Anchor = {hex: string, meaning: string, as: 'scale' | 'slot', ladder: string}

/** family or Nuxt UI slot → the anchor it takes */
export type HueMap = Record<string, Anchor>

export type Preset = {
    name: string
    level: Level
    /** Bumped when the preset is regenerated, so a rerun that changes nothing changes no byte */
    generatedOn: string
    hues: HueMap
    /** The lines of the file's opening comment, between `/*` and the closing marker */
    header: (output: string, generatedOn: string) => string[]
}

const tydeligHeader = (output: string, generatedOn: string) => [
    ' * Tydelig - the AA palette preset. GENERATED by scripts/palettes/generate.ts; edits are overwritten.',
    ' *',
    ` * Generated ${generatedOn} against EN 301 549 → WCAG 2.1: 4.5:1 body text and 3:1 large-scale`,
    ' * text (1.4.3 AA), 3:1 borders, rings and UI boundaries (1.4.11 AA). The hues and the chroma are',
    ' * TheSlope\'s published palette; only OKLCH lightness moves, and the neutral surfaces stay put.',
    ' *',
    ' * A `--ui-<slot>` line re-points a Nuxt UI semantic slot at another rung of its own family,',
    ' * so a white button label is answered by the slot rather than by the rung the brand paints with.',
    ' *',
    ` * Run: npx jiti scripts/palettes/generate.ts     # rewrites ${output}`
]

const colorblindHeader = (output: string, generatedOn: string) => [
    ' * Farveblind - the colour-safe AA palette preset. GENERATED by scripts/palettes/generate.ts;',
    ' * edits are overwritten.',
    ' *',
    ` * Generated ${generatedOn}. The meaning-bearing families take the Color Universal Design`,
    ' * (Okabe & Ito) anchors, which stay apart under protanopia, deuteranopia and tritanopia:',
    ' * success bluish green #009E73, error vermillion #D55E00, warning orange #E69F00, deadline',
    ' * chips yellow #F0E442, the info slot blue #0072B2, secondary and the cooking day reddish',
    ' * purple #CC79A7. Each anchor keeps its hue and chroma and walks the published family\'s',
    ' * lightness ladder, chroma clamped to the sRGB gamut per rung.',
    ' *',
    ' * The info slot is published as `--ui-color-info-<step>`, so `bg-info` and `text-info-600`',
    ' * take the blue while `--color-violet-*` keeps painting the Bonbon band and chip.',
    ' *',
    ' * On top of the hue map the preset meets EN 301 549 → WCAG 2.1: 4.5:1 body text and 3:1',
    ' * large-scale text (1.4.3 AA), 3:1 borders, rings and UI boundaries (1.4.11 AA), in both modes.',
    ' * A `--ui-<slot>` line re-points a Nuxt UI semantic slot at another rung of its own family,',
    ' * so a white button label is answered by the slot rather than by the rung the brand paints with.',
    ' *',
    ` * Run: npx jiti scripts/palettes/generate.ts     # rewrites ${output}`
]

/**
 * Farveblind's hue map. The brand families stay put - mocha, ocean, party, peach, caramel, winery,
 * sky and the Bonbon violet - so the rainbow, the chips and the team colours are unchanged.
 * Orange is both band 1 and the warning slot, and the anchor sits 36° from Mandarin Orange, so the
 * scale moves and the band moves with it; violet is both band 3 and the info slot, and the anchor
 * sits 110° away, so the slot moves alone.
 */
const COLORBLIND_HUES: HueMap = {
    green: {hex: '#009E73', meaning: 'success, active season, CHILD ticket, holiday ring', as: 'scale', ladder: 'green'},
    red: {hex: '#D55E00', meaning: 'error, released orders, cancellations, delete confirm', as: 'scale', ladder: 'red'},
    orange: {hex: '#E69F00', meaning: 'warning, power mode, deadline ring, CTAs', as: 'scale', ladder: 'orange'},
    yellow: {hex: '#F0E442', meaning: 'deadline chips', as: 'scale', ladder: 'yellow'},
    pink: {hex: '#CC79A7', meaning: 'secondary, generated cooking days, picker selection', as: 'scale', ladder: 'pink'},
    info: {hex: '#0072B2', meaning: 'info alerts, guest rows, claimed orders', as: 'slot', ladder: 'violet'}
}

export const PRESETS: Preset[] = [
    {name: 'tydelig', level: 'AA', generatedOn: '2026-09-17', hues: {}, header: tydeligHeader},
    {name: 'colorblind', level: 'AA', generatedOn: '2026-09-18', hues: COLORBLIND_HUES, header: colorblindHeader}
]
